name: Just test
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    branches:
      - '*'
jobs:
  User-service-tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - name: Checkout
        uses: actions/checkout@main
      - name: Install requirements
        run: |
          cd server_user
          npm i
      - name: Run tests
        run: |
          cd server_user
          npm run test