name: Just test
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    branches:
      - '*'
jobs:
  User-service-tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - name: Checkout
        uses: actions/checkout@main
      - name: Build docker
        run: |
          cd postgres
          docker build . -t postgres-db
          docker run --name postgres-db-container --network server-network -p 5432:5432 -d postgres-db
      - name: Install requirements
        run: |
          cd server_user
          npm i
      - name: Run tests
        run: |
          cd server_user
          npm run test